#!/usr/bin/env bash
#
# Create a christmas tree on the terminal
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: December 24, 2024
# License: MIT

# colors
COLOR_TREE=$(tput setaf 2)
COLOR_STAR=$(tput setaf 227)

# lights - dave matched these to "vintaglo vintage christmas lights"
COLOR_LIGHTS=(
	"$(tput setaf 111)"
	"$(tput setaf 208)"
	"$(tput setaf 198)"
	"$(tput setaf 155)"
)
COLOR_LIGHTS_LEN=${#COLOR_LIGHTS[@]}

# the tree itself - each number represents a specific "light" color
IFS= read -r -d '' TREE <<-"EOF"
          *
         / \
        / 0 \
       / 1   \
      /       \
     /_ 2  1  _\
      /       \
     /  1   2  \
    /           \
   /   0  3  0   \
  /_        1    _\
   /    2        \
  /  1   0   0    \
 /    3         3  \
/  2        1       \
---------------------
         |||
        /|||\
EOF
TREE_HEIGHT=18
TREE_WIDTH=20

MESSAGE=(
	"${COLOR_LIGHTS[3]}Merry Christmas!"
	"${COLOR_LIGHTS[3]}From Dave Eddy"
	"${COLOR_LIGHTS[1]}$ ${COLOR_LIGHTS[0]}curl ysap.sh"
)

tput() {
#	sleep .1
	command tput "$@"
}

cleanup() {
	tput rmcup
	tput cnorm
}

main() {
	# configure terminal for drawing
	trap cleanup exit
	tput smcup
	tput civis

	# figure out our size
	COLUMNS=$(tput cols)
	LINES=$(tput lines)

	local middle_y=$((LINES / 2 - (TREE_HEIGHT / 2)))
	local middle_x=$((COLUMNS / 2 - (TREE_WIDTH / 2)))

	# current color index
	local idx=0
	local t x y
	while true; do
		# stylize and colorize tree
		t=$COLOR_TREE$TREE
		t=${t// \*/ ${COLOR_STAR}*${COLOR_TREE} }
		t=${t// 0 / ${COLOR_LIGHTS[idx % COLOR_LIGHTS_LEN]}o${COLOR_TREE} }
		t=${t// 1 / ${COLOR_LIGHTS[(idx + 1) % COLOR_LIGHTS_LEN]}o${COLOR_TREE} }
		t=${t// 2 / ${COLOR_LIGHTS[(idx + 2) % COLOR_LIGHTS_LEN]}o${COLOR_TREE} }
		t=${t// 3 / ${COLOR_LIGHTS[(idx + 3) % COLOR_LIGHTS_LEN]}o${COLOR_TREE} }

		# display the tree
		x=$((middle_x - 10))
		y=$middle_y
		while IFS= read -r line; do
			tput cup "$y" "$x"
			echo -n "$line"
			((y++))
		done <<< "$t"
	#	echo "$t"

		# display the text
		x=$((middle_x + 12))
		y=$((middle_y + 7))
		for line in "${MESSAGE[@]}"; do
			tput cup "$y" "$x"
			echo -n "$line"
			((y++))
		done

		# increment the lights and pause for the animation to play
		((idx++))
		sleep 1
	done
}

main "$@"
